server:
  port: 8080
spring:
  freemarker:
    suffix: .html
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://112.74.181.231:3306/mpp?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&serverTimezone=GMT%2B8&tinyInt2isBit=false
    driver-class-name: com.mysql.jdbc.Driver
mybatis:
  mapper-locations: classpath:mapper/*.xml
